---
# see: https://github.com/bitnami/charts/blob/main/bitnami/wordpress/values.yaml
wordpressPassword: password

service:
  type: NodePort

persistence:
  storageClass: standard
  size: 500Mi
volumePermissions:
  enabled: true

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

mariadb:
  primary:
    persistence:
      storageClass: standard
      size: 500Mi
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
