---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: wordpress-frontend-config
  namespace: wordpress-argocd
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
