---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    name: Lint YAML

    steps:
      - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - run: |
          yamllint .

  tflint:
    runs-on: ubuntu-latest
    name: Lint Terraform

    steps:
      - uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6

      - run: |
          tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          tflint
        working-directory: ./bootstrap/gke
